import { SERVICE_LINES } from "../shared/types";

export function getOpenApiDocument() {
  return {
    openapi: "3.1.0",
    info: {
      title: "Resident OR Coverage Planner API",
      version: "0.1.0",
      description:
        "API for viewing and editing resident OR coverage planner data. Use X-API-Key for external tools and MCP servers, or a browser login token for app sessions."
    },
    servers: [
      {
        url: process.env.PUBLIC_BASE_URL || "/"
      }
    ],
    security: [{ ApiKeyAuth: [] }, { BearerAuth: [] }],
    components: {
      securitySchemes: {
        ApiKeyAuth: {
          type: "apiKey",
          in: "header",
          name: "X-API-Key"
        },
        BearerAuth: {
          type: "http",
          scheme: "bearer"
        }
      },
      parameters: {
        StateVersionHeader: {
          name: "X-State-Version",
          in: "header",
          required: false,
          schema: { type: "number" },
          description: "PlannerState.version from the latest GET /api/state. Stale values return 409 with currentVersion."
        }
      },
      schemas: {
        LoginRequest: {
          type: "object",
          required: ["username", "password"],
          properties: {
            username: { type: "string" },
            password: { type: "string" }
          }
        },
        LoginResponse: {
          type: "object",
          properties: {
            token: { type: "string" },
            username: { type: "string" },
            displayName: { type: "string" },
            role: { type: "string", enum: ["admin", "viewer"] },
            servicePrivileges: {
              type: "object",
              additionalProperties: { type: "string", enum: ["view", "request", "edit"] }
            },
            passwordUpdatedAt: { type: "string", format: "date-time" },
            mustChangePassword: { type: "boolean" },
            temporaryPasswordExpiresAt: { type: "string", format: "date-time" }
          }
        },
        UserSummary: {
          type: "object",
          properties: {
            username: { type: "string" },
            displayName: { type: "string" },
            role: { type: "string", enum: ["admin", "viewer"] },
            servicePrivileges: {
              type: "object",
              additionalProperties: { type: "string", enum: ["view", "request", "edit"] }
            },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
            passwordUpdatedAt: { type: "string", format: "date-time" },
            mustChangePassword: { type: "boolean" },
            temporaryPasswordExpiresAt: { type: "string", format: "date-time" }
          }
        },
        UserInput: {
          type: "object",
          required: ["username"],
          properties: {
            username: { type: "string" },
            displayName: { type: "string" },
            role: { type: "string", enum: ["admin", "viewer"] },
            password: { type: "string", description: "Optional. Omit to generate a one-time temporary password." },
            servicePrivileges: {
              type: "object",
              additionalProperties: { type: "string", enum: ["view", "request", "edit"] }
            }
          }
        },
        UserCreationResult: {
          type: "object",
          properties: {
            user: { $ref: "#/components/schemas/UserSummary" },
            temporaryPassword: {
              type: "string",
              description: "Returned once when the password was generated by the server."
            }
          }
        },
        ErrorResponse: {
          type: "object",
          properties: {
            error: { type: "string" }
          }
        },
        ConflictResponse: {
          type: "object",
          properties: {
            error: { type: "string" },
            currentVersion: { type: "number" }
          }
        },
        AssignmentInput: {
          type: "object",
          required: ["kind", "targetId", "residentId"],
          properties: {
            kind: { type: "string", enum: ["case", "block", "clinic"] },
            targetId: { type: "string" },
            residentId: { type: "string" },
            locked: { type: "boolean", default: false }
          }
        },
        ClaimInput: {
          type: "object",
          required: ["scope", "targetId", "residentId"],
          properties: {
            scope: { type: "string", enum: ["case", "block"] },
            targetId: { type: "string" },
            residentId: { type: "string" }
          }
        },
        CoverageEntryInput: {
          type: "object",
          required: ["date", "kind"],
          properties: {
            date: { type: "string", format: "date" },
            kind: { type: "string", enum: ["call", "rounding", "off", "note"] },
            residentId: { type: "string" },
            note: { type: "string" }
          }
        },
        CoverageRequestInput: {
          type: "object",
          required: ["action"],
          properties: {
            serviceLine: { type: "string", enum: [...SERVICE_LINES] },
            requestType: { type: "string", enum: ["calendar", "resident-trade"], default: "calendar" },
            action: { type: "string", enum: ["create", "update", "delete"] },
            entryId: { type: "string" },
            requestedEntry: { $ref: "#/components/schemas/CoverageEntryInput" },
            targetResidentId: { type: "string", description: "For resident-trade requests, the resident being asked to accept the trade." },
            swapEntryId: { type: "string", description: "Optional resident-trade entry owned by targetResidentId to swap back to the requester." },
            requesterName: { type: "string" },
            message: { type: "string" }
          }
        }
      }
    },
    paths: {
      "/api/healthz": {
        get: {
          summary: "Health check",
          security: [],
          responses: {
            "200": {
              description: "Server is healthy"
            }
          }
        }
      },
      "/api/openapi.json": {
        get: {
          summary: "OpenAPI document",
          security: [],
          responses: {
            "200": {
              description: "OpenAPI JSON"
            }
          }
        }
      },
      "/api/auth/login": {
        post: {
          summary: "Create a browser-session bearer token",
          security: [],
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/LoginRequest" }
              }
            }
          },
          responses: {
            "200": {
              description: "Login token",
              content: {
                "application/json": {
                  schema: { $ref: "#/components/schemas/LoginResponse" }
                }
              }
            },
            "401": { description: "Invalid login" }
          }
        }
      },
      "/api/session": {
        get: {
          summary: "Show authenticated role",
          responses: {
            "200": { description: "Current role and auth type" },
            "401": { description: "Unauthorized" }
          }
        }
      },
      "/api/events": {
        get: {
          summary: "Subscribe to planner state updates",
          description: "Server-Sent Events stream. Browser EventSource clients pass a bearer token as ?token= because EventSource cannot set Authorization headers.",
          parameters: [{ name: "token", in: "query", required: false, schema: { type: "string" } }],
          responses: {
            "200": { description: "text/event-stream with state version events" },
            "401": { description: "Unauthorized" }
          }
        }
      },
      "/api/users": {
        get: {
          summary: "List browser users",
          description: "Admin-only and protected by the users pin code.",
          parameters: [{ name: "pin", in: "query", required: true, schema: { type: "string" } }],
          responses: {
            "200": {
              description: "User list",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: {
                      users: { type: "array", items: { $ref: "#/components/schemas/UserSummary" } }
                    }
                  }
                }
              }
            },
            "403": { description: "Invalid pin or non-admin user" }
          }
        },
        post: {
          summary: "Create browser user",
          description:
            "Admin-only and protected by the users pin code. Omit password to generate a temporary password returned once and force a password change on next login.",
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: {
                  allOf: [
                    { $ref: "#/components/schemas/UserInput" },
                    {
                      type: "object",
                      required: ["pin"],
                      properties: { pin: { type: "string" } }
                    }
                  ]
                }
              }
            }
          },
          responses: {
            "201": {
              description: "Created user, optional temporary password, and refreshed user list",
              content: {
                "application/json": {
                  schema: {
                    allOf: [
                      { $ref: "#/components/schemas/UserCreationResult" },
                      {
                        type: "object",
                        properties: {
                          users: { type: "array", items: { $ref: "#/components/schemas/UserSummary" } }
                        }
                      }
                    ]
                  }
                }
              }
            },
            "403": { description: "Invalid pin or non-admin user" }
          }
        }
      },
      "/api/users/bulk": {
        post: {
          summary: "Create multiple browser users",
          description:
            "Admin-only and protected by the users pin code. Creates all users in one batch and returns generated temporary passwords once.",
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  required: ["pin", "users"],
                  properties: {
                    pin: { type: "string" },
                    users: { type: "array", items: { $ref: "#/components/schemas/UserInput" } }
                  }
                }
              }
            }
          },
          responses: {
            "201": {
              description: "Created users and refreshed user list",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    properties: {
                      created: { type: "array", items: { $ref: "#/components/schemas/UserCreationResult" } },
                      users: { type: "array", items: { $ref: "#/components/schemas/UserSummary" } }
                    }
                  }
                }
              }
            },
            "403": { description: "Invalid pin or non-admin user" }
          }
        }
      },
      "/api/users/{username}": {
        patch: {
          summary: "Update browser user privileges",
          description: "Admin-only and protected by the users pin code.",
          parameters: [{ name: "username", in: "path", required: true, schema: { type: "string" } }],
          responses: {
            "200": { description: "Updated user and refreshed user list" },
            "403": { description: "Invalid pin or non-admin user" }
          }
        },
        delete: {
          summary: "Delete browser user",
          description: "Admin-only and protected by the users pin code. The built-in admin account cannot be deleted.",
          parameters: [{ name: "username", in: "path", required: true, schema: { type: "string" } }],
          responses: {
            "200": { description: "Refreshed user list" },
            "403": { description: "Invalid pin or non-admin user" }
          }
        }
      },
      "/api/users/{username}/password": {
        patch: {
          summary: "Generate a temporary password",
          description:
            "Admin-only and protected by the users pin code. Generates a temporary password, returns it once, stores only its hash, and requires the user to change it on next login.",
          parameters: [{ name: "username", in: "path", required: true, schema: { type: "string" } }],
          responses: {
            "200": { description: "Temporary password, updated user, and refreshed user list" },
            "403": { description: "Invalid pin or non-admin user" }
          }
        }
      },
      "/api/users-pin": {
        patch: {
          summary: "Change users-tab pin code",
          description: "Admin-only. Requires currentPin and nextPin in the JSON body.",
          responses: {
            "200": { description: "Pin changed" },
            "403": { description: "Non-admin user" }
          }
        }
      },
      "/api/me/password": {
        patch: {
          summary: "Change current browser user's password",
          responses: {
            "200": { description: "Password changed" },
            "401": { description: "Unauthorized" }
          }
        }
      },
      "/api/state": {
        get: {
          summary: "Get complete planner state",
          description: "Best endpoint for AI tools that need a full current snapshot.",
          responses: {
            "200": { description: "PlannerState JSON" },
            "401": { description: "Unauthorized" }
          }
        }
      },
      "/api/weeks/{weekId}/schedule": {
        get: {
          summary: "Get computed weekly schedule",
          parameters: [
            { name: "weekId", in: "path", required: true, schema: { type: "string" } },
            { name: "service", in: "query", required: false, schema: { type: "string", enum: [...SERVICE_LINES] } }
          ],
          responses: {
            "200": { description: "WeekSchedule JSON with computed case times and warnings" }
          }
        }
      },
      "/api/weeks/{weekId}/warnings": {
        get: {
          summary: "Get assignment warnings",
          parameters: [
            { name: "weekId", in: "path", required: true, schema: { type: "string" } },
            { name: "service", in: "query", required: false, schema: { type: "string", enum: [...SERVICE_LINES] } }
          ],
          responses: {
            "200": { description: "Warning array" }
          }
        }
      },
      "/api/weeks/{weekId}/uncovered-message": {
        get: {
          summary: "Generate uncovered coverage text",
          parameters: [
            { name: "weekId", in: "path", required: true, schema: { type: "string" } },
            { name: "date", in: "query", required: false, schema: { type: "string", format: "date" } },
            { name: "service", in: "query", required: false, schema: { type: "string", enum: [...SERVICE_LINES] } }
          ],
          responses: {
            "200": { description: "Copyable uncovered message" }
          }
        }
      },
      "/api/residents/{residentId}/calendar.ics": {
        get: {
          summary: "Export a resident calendar feed",
          description: "Returns text/calendar with OR, clinic, call, rounding, off, and note entries. Non-admin users can export only their linked resident profile.",
          parameters: [
            { name: "residentId", in: "path", required: true, schema: { type: "string" } },
            { name: "token", in: "query", required: false, schema: { type: "string" } }
          ],
          responses: {
            "200": { description: "ICS calendar feed" },
            "403": { description: "Calendar export is not allowed for this user" },
            "404": { description: "Resident not found" }
          }
        }
      },
      "/api/weeks/{weekId}/suggest": {
        post: {
          summary: "Run schedule suggestion",
          description: "Admin only. Preserves locked/manual assignments and fills uncovered cases/clinics.",
          parameters: [
            { name: "weekId", in: "path", required: true, schema: { type: "string" } },
            { name: "service", in: "query", required: false, schema: { type: "string", enum: [...SERVICE_LINES] } }
          ],
          responses: {
            "200": { description: "Updated PlannerState" },
            "403": { description: "Admin access required" }
          }
        }
      },
      "/api/entities/{collection}": {
        post: {
          summary: "Create an entity",
          description:
            "Admin only. Collection must be one of hospitals, attendings, residents, procedureDefaults, weeks, attendingBlocks, cases, clinicSessions.",
          parameters: [{ name: "collection", in: "path", required: true, schema: { type: "string" } }],
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: { type: "object", additionalProperties: true }
              }
            }
          },
          responses: {
            "201": { description: "Updated PlannerState" },
            "403": { description: "Admin access required" }
          }
        }
      },
      "/api/entities/{collection}/{id}": {
        patch: {
          summary: "Patch an entity",
          description: "Admin only. Partial updates are merged into the entity with the matching id.",
          parameters: [
            { name: "collection", in: "path", required: true, schema: { type: "string" } },
            { name: "id", in: "path", required: true, schema: { type: "string" } }
          ],
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: { type: "object", additionalProperties: true }
              }
            }
          },
          responses: {
            "200": { description: "Updated PlannerState" },
            "403": { description: "Admin access required" }
          }
        },
        delete: {
          summary: "Delete an entity",
          description: "Admin only.",
          parameters: [
            { name: "collection", in: "path", required: true, schema: { type: "string" } },
            { name: "id", in: "path", required: true, schema: { type: "string" } }
          ],
          responses: {
            "200": { description: "Updated PlannerState" },
            "403": { description: "Admin access required" }
          }
        }
      },
      "/api/assignments": {
        post: {
          summary: "Create or replace an assignment",
          description:
            "Requires edit privilege for the assignment target service, or admin/API admin access. Case and block assignments replace same-target assignments. Creating a block assignment clears case-level assignments within that block.",
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/AssignmentInput" }
              }
            }
          },
          responses: {
            "201": { description: "Updated PlannerState" },
            "403": { description: "Edit privilege required" }
          }
        }
      },
      "/api/assignments/{id}": {
        patch: {
          summary: "Patch an assignment",
          description: "Requires edit privilege for the assignment target service, or admin/API admin access. Use this to change residentId or locked status.",
          parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }],
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: { type: "object", additionalProperties: true }
              }
            }
          },
          responses: {
            "200": { description: "Updated PlannerState" }
          }
        },
        delete: {
          summary: "Delete an assignment",
          description: "Requires edit privilege for the assignment target service, or admin/API admin access.",
          parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }],
          responses: {
            "200": { description: "Updated PlannerState" }
          }
        }
      },
      "/api/claims": {
        post: {
          summary: "Viewer/admin claim uncovered coverage",
          description:
            "Requires edit privilege for the target service, or admin/API admin access. Auto-assigns the selected resident to an uncovered case or block and records activity.",
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/ClaimInput" }
              }
            }
          },
          responses: {
            "201": { description: "Updated PlannerState" }
          }
        }
      },
      "/api/coverage-entries": {
        post: {
          summary: "Create or replace a call calendar entry",
          description:
            "Requires edit privilege for serviceLine, or admin/API admin access. Call is allowed Friday-Sunday; rounding is allowed Saturday-Sunday. Call/rounding entries replace the same date/kind slot.",
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/CoverageEntryInput" }
              }
            }
          },
          responses: {
            "201": { description: "Updated PlannerState" },
            "403": { description: "Edit privilege required" }
          }
        }
      },
      "/api/coverage-entries/{id}": {
        patch: {
          summary: "Patch a call calendar entry",
          description: "Requires edit privilege for serviceLine, or admin/API admin access.",
          parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }],
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: { type: "object", additionalProperties: true }
              }
            }
          },
          responses: {
            "200": { description: "Updated PlannerState" },
            "403": { description: "Edit privilege required" }
          }
        },
        delete: {
          summary: "Delete a call calendar entry",
          description: "Requires edit privilege for serviceLine, or admin/API admin access.",
          parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }],
          responses: {
            "200": { description: "Updated PlannerState" },
            "403": { description: "Edit privilege required" }
          }
        }
      },
      "/api/coverage-requests": {
        post: {
          summary: "Submit a calendar edit request",
          description: "Default calendar requests require request or edit privilege for serviceLine and are resolved by a service editor. Resident-trade requests use requestType=resident-trade, must come from the linked resident who owns entryId, and are resolved by targetResidentId.",
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/CoverageRequestInput" }
              }
            }
          },
          responses: {
            "201": { description: "Updated PlannerState" }
          }
        }
      },
      "/api/coverage-requests/{id}/approve": {
        post: {
          summary: "Approve and apply a calendar request",
          description: "Requires edit privilege for the request serviceLine, admin/API admin access, or the target resident on a resident-trade request.",
          parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }],
          responses: {
            "200": { description: "Updated PlannerState" },
            "403": { description: "Edit privilege required" }
          }
        }
      },
      "/api/coverage-requests/{id}/deny": {
        post: {
          summary: "Deny a calendar request",
          description: "Requires edit privilege for the request serviceLine, admin/API admin access, or the target resident on a resident-trade request.",
          parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }],
          responses: {
            "200": { description: "Updated PlannerState" },
            "403": { description: "Edit privilege required" }
          }
        }
      }
    }
  };
}
